pub const ERR_ENV_NOT_LOADED: i32 = 10;
pub const ERR_ROCKET_NOT_BUILT: i32 = 11;
pub const ERR_PRE_RUNTIME_ERROR: i32 = 12;
pub const ERR_ROCKET_IGNITION_FAILED: i32 = 13;
pub const ERR_ROCKET_LAUNCH_FAILED: i32 = 14;
pub const ERR_COMMAND_REGISTRY_NOT_FOUND: i32 = 15;
pub const ERR_COMMAND_NOT_FOUND: i32 = 16;
pub const ERR_COMMAND_FAILED: i32 = 17;
pub const ERR_COMMAND_SKIPPED: i32 = 18;

pub const ERR_UNKNOWN_RUNTIME_ERROR: i32 = 99;
