mindmap
  root((HERMES))
    %% technos
    Rust
        CLI
            Serveur
            Console
            "CLAP"
    SurrealDB
        Lancer un serveur à côté
            Conteneur
        Gestion des modèles
    %% concepts
    Serveur HTTP
        "Rocket"
    Sous domaine + site statique
        Préciser la racine des sites
        Sécuriser l'accès aux fichiers
            Statuts HTTP
    authentification
        Login + password
        argon2id
        poser un cookie pour le subdomain
    API
        Sécurité
            header avec clé
        Format
            REST
                JSON
        Manipulation des accès